database:
  driver: postgres
  host: akrab-398216-34-101-160-121.akrablocal.windows.net
  port: 5432
  user: postgres
  password: 86f7e437faa5a7fce15d1ddcb9eaeaea377667b8
  dbname: akrablocal
  sslmode: require
  schema:
    app: app
server:
  port: 8082
  env: development
  baseurl: http://localhost:8082/
  redirectpage: http://localhost:8082/
