database:
  driver: postgres
  host: 34.101.160.121
  port: 5432
  user: postgres
  password: a
  dbname: akrablocal
  sslmode: prefer
  schema:
    app: public
server:
  port: 8082
  env: development
  baseurl: http://localhost:8082/
  redirectpage: http://localhost:8082/
